### ISSUE TITLE
Unable to run with Lightning

### ISSUE THREAD

**Issue by louisvangeldrop** [ms-iot/vscode#15]
uwp.projectNamespace('Microsoft');
// Check if Lightning is enabled and set the Lightning provider as the default provider
try {
    if (Microsoft.IoT.Lightning.Providers.LightningProvider.isLightningEnabled) {
        Windows.Devices.LowLevelDevicesController.defaultProvider = Microsoft.IoT.Lightning.Providers.LightningProvider.getAggregateProvider();
    }
}
catch (error) {
    console.log(`error in Lightning: ${error}`)
}
finally { 
  }

**Comment by IoTGirl** [comment]
Hi Louis,
I am afraid there is not enough detail here as to what exact issue you are hitting so I am closing this issue. If future please provide:
1. Details for your setup : Device and OS versions as well as everything you have connected
2. A full set of steps someone can follow to see your issue
3. Actual outcome with all error codes 
4. expected outcome detailing what you actually expected to happen.
Sincerely,
IoTGirl
